name: 'Verify Pull Request Labels'
description: 'Verify that the PR has a valid label'
inputs:
  github-token:
    description: 'The GitHub token'
    required: true
  valid-labels:
    description: 'List of valid labels'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.valid-labels }}